<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @PropertyStrategy('ckDoctrinePropertyStrategy')
 */
class DoctrineArticleAuthor extends BaseDoctrineArticleAuthor
{

}