<?php
/**
 * This file is part of the ckWebServicePlugin
 *
 * @package   ckWebServicePlugin
 * @author    Christian Kerl <christian-kerl@web.de>
 * @copyright Copyright (c) 2009, Christian Kerl
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 * @version   SVN: $Id$
 */

/**
 * ckGenericObjectAdapterFactory
 *
 * @package    ckWebServicePlugin
 * @subpackage adapter
 * @author     Christian Kerl <christian-kerl@web.de>
 */
class ckGenericObjectAdapterFactory
{
  protected static $CLASS = 'ckGenericObjectAdapter';

  public function __construct()
  {
  }

  public function autoload($class)
  {
    if(!$this->isGenericObjectAdapter($class))
    {
      return false;
    }

    return $this->loadCachedClassFile($this->getAdaptedClass($class));
  }

  protected function isGenericObjectAdapter($class)
  {
    return ckString::startsWith($class, self::$CLASS . '_');
  }

  protected function getAdaptedClass($class)
  {
    return substr($class, strlen(self::$CLASS . '_'));
  }

  protected function getCacheFile($class)
  {
    $dir = sprintf('%s/ckWebServicePlugin/%s', sfConfig::get('sf_cache_dir'), self::$CLASS);

    if(!file_exists($dir))
    {
      mkdir($dir, 0777, true);
    }

    return sprintf('%s/%s.php', $dir, $class);
  }

  protected function loadCachedClassFile($class)
  {
    $cacheFile = $this->getCacheFile($class);

    if(!file_exists($cacheFile))
    {
      file_put_contents($cacheFile, $this->buildClassDefinition($class));
    }

    return require_once($cacheFile);
  }

  protected function buildClassDefinition($class)
  {
    return sprintf('<?php
// auto-generated by %1$sFactory
// date: %2$s

class %1$s_%3$s extends %1$s
{
  protected function initializeObject()
  {
    return new %3$s();
  }
}', self::$CLASS, date('Y/m/d H:i:s'), $class);
  }
}