<?php

/**
 * BaseAuthor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Articles
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getArticles() Returns the current record's "Articles" collection
 * @method Author              setName()     Sets the current record's "name" value
 * @method Author              setArticles() Sets the current record's "Articles" collection
 * 
 * @package    projectWithDoctrine
 * @subpackage model
 * @author     Christian Kerl
 * @version    SVN: $Id$
 */
abstract class BaseAuthor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('author');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'refClass' => 'ArticleAuthor',
             'local' => 'article_id',
             'foreign' => 'author_id'));
    }
}