<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property string $author
 * @property clob $content
 * @property Article $Article
 * 
 * @method integer getArticleId()  Returns the current record's "article_id" value
 * @method string  getAuthor()     Returns the current record's "author" value
 * @method clob    getContent()    Returns the current record's "content" value
 * @method Article getArticle()    Returns the current record's "Article" value
 * @method Comment setArticleId()  Sets the current record's "article_id" value
 * @method Comment setAuthor()     Sets the current record's "author" value
 * @method Comment setContent()    Sets the current record's "content" value
 * @method Comment setArticle()    Sets the current record's "Article" value
 * 
 * @package    projectWithDoctrine
 * @subpackage model
 * @author     Christian Kerl
 * @version    SVN: $Id$
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));
    }
}