<?php

/**
 * Comment
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    projectWithDoctrine
 * @subpackage model
 * @author     Christian Kerl
 * @version    SVN: $Id$
 *
 * @PropertyStrategy('ckDoctrinePropertyStrategy')
 */
class Comment extends BaseComment
{

}