<?php


/**
 * Skeleton subclass for representing a row from the 'author' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 01/10/10 00:58:42
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 *
 * @PropertyStrategy('ckPropelPropertyStrategy')
 */
class Author extends BaseAuthor {

} // Author
